---
services:
  ombi:
    network_mode: bridge
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /data/servers/ombi:/config
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.protocol=http
      - traefik.http.middlewares.ombi-whitelist.ipwhitelist.sourcerange=127.0.0.1/32, 192.168.0.0/16, 172.0.0.0/8, 0.0.0.0/0
      - traefik.http.routers.ombi.rule=Host(`ombi.yourdomain.com`) || Host(`requests.yourdomain.com`)
      - traefik.http.routers.ombi.entrypoints=websecure
      - traefik.http.services.ombi.loadbalancer.server.port=3579
      - traefik.http.routers.ombi.service=ombi
      - traefik.http.routers.ombi.tls.certresolver=mydnschallenge
      - traefik.http.routers.ombi.middlewares=ombi-whitelist
